[tool.poetry]
name = "projetodatastack"
version = "0.1.0"
description = ""
authors = ["Matheus Galvão <Matheusgalvaoangelo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "==3.11.5"
apache-airflow = "^2.9.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
